




// ______________________________________________________
// Generated by sql2java - http://sql2java.sourceforge.net/
// jdbc driver used at code generation time: com.mysql.jdbc.Driver
//
// Author: Javed Kansi
// ______________________________________________________

package uk.co.planetbeyond.service.managedbean;

import uk.co.planetbeyond.service.generated.AdvertScheduleBean;
import com.sleepycat.persist.model.Persistent;

/**
* If any changes needs to be made to the AdvertScheduleBean, it MUST not be made directly to AdvertScheduleBean
* Instead the AdvertScheduleManagedBean should be used to make the changes
*/
@Persistent
public class AdvertScheduleManagedBean extends AdvertScheduleBean
{
	private static final long serialVersionUID = 3486133106571759174L;

	/**
	* Make the constructor public so that it can be accessed externally
	*/
	public AdvertScheduleManagedBean()
	{
		super();
	}
}
