// ______________________________________________________
// Generated by sql2java - http://sql2java.sourceforge.net/
// jdbc driver used at code generation time: $db.Driver
//
// Author: Javed Kansi
// ______________________________________________________

package uk.co.planetbeyond.service.managedbean;

import com.sleepycat.persist.model.Persistent;

/**
 * If there is any functionality that needs to be added to all beans, add it here since all beans extends this class
 *
 * @author sql2java
 * @version $Revision: 1.3 $
 */
@Persistent
public abstract class BaseBean 
{

}
