




// ______________________________________________________
// Generated by sql2java - http://sql2java.sourceforge.net/
// jdbc driver used at code generation time: com.mysql.jdbc.Driver
//
// Author: Javed Kansi
// ______________________________________________________

package uk.co.planetbeyond.service.managedbean;

import uk.co.planetbeyond.service.generated.LoyaltyStatsBean;
import com.sleepycat.persist.model.Persistent;

/**
* If any changes needs to be made to the LoyaltyStatsBean, it MUST not be made directly to LoyaltyStatsBean
* Instead the LoyaltyStatsManagedBean should be used to make the changes
*/
@Persistent
public class LoyaltyStatsManagedBean extends LoyaltyStatsBean
{
	private static final long serialVersionUID = 3072311189420128425L;

	/**
	* Make the constructor public so that it can be accessed externally
	*/
	public LoyaltyStatsManagedBean()
	{
		super();
	}
}
