




// ______________________________________________________
// Generated by sql2java - http://sql2java.sourceforge.net/
// jdbc driver used at code generation time: com.mysql.jdbc.Driver
//
// Author: Javed Kansi
// ______________________________________________________

package uk.co.planetbeyond.service.manager;

import uk.co.planetbeyond.service.generated.AdvertisementManager;
import uk.co.planetbeyond.service.generated.AdvertisementBean;
import uk.co.planetbeyond.service.managedbean.AdvertisementManagedBean;

/**
* If any change needs to be made to the AdvertisementManager, it MUST not be made directly
* Instead the AdvertisementManagerImpl class should be used to make the changes
*/
public class AdvertisementManagerImpl extends AdvertisementManager 
{
	/**
	* Singleton instance of this class
	*/
	private static AdvertisementManagerImpl singleton = new AdvertisementManagerImpl();
	
	/**
	* Make the constructor private to make the class singleton
	*/
	private AdvertisementManagerImpl()
	{
		super();
		
		// set the singleton instance of AdvertisementManagerImpl class in the AdvertisementManager so that
		// AdvertisementManager.getInstance() also points to the singleton instance of AdvertisementManagerImpl 
		setInstance(this);
	}
	
	/**
	* To make the singleton instance available to external classes
	*/
	public static AdvertisementManagerImpl getInstance()
	{
		return singleton;
	}

	/**
	* Override this method so that it returns an instance of AdvertisementManagedBean instead of AdvertisementBean
	*/
	@Override
	public AdvertisementBean createAdvertisementBean()
	{
		return new AdvertisementManagedBean();
	}   
}
