// ______________________________________________________
// Generated by sql2java - http://sql2java.sourceforge.net/
// jdbc driver used at code generation time: com.mysql.jdbc.Driver
//
// Author: Javed Kansi
// ______________________________________________________

package uk.co.planetbeyond.service.manager;

/**
 * If there is any functionality that needs to be added to all managers, add it here since all managers extends this class
 *
 * @author sql2java
 * @version $Revision: 1.3 $
 */
public abstract class BaseManager 
{

}
