




// ______________________________________________________
// Generated by sql2java - http://sql2java.sourceforge.net/
// jdbc driver used at code generation time: com.mysql.jdbc.Driver
//
// Author: Javed Kansi
// ______________________________________________________

package uk.co.planetbeyond.service.manager;

import uk.co.planetbeyond.service.generated.ClientManager;
import uk.co.planetbeyond.service.generated.ClientBean;
import uk.co.planetbeyond.service.managedbean.ClientManagedBean;

/**
* If any change needs to be made to the ClientManager, it MUST not be made directly
* Instead the ClientManagerImpl class should be used to make the changes
*/
public class ClientManagerImpl extends ClientManager 
{
	/**
	* Singleton instance of this class
	*/
	private static ClientManagerImpl singleton = new ClientManagerImpl();
	
	/**
	* Make the constructor private to make the class singleton
	*/
	private ClientManagerImpl()
	{
		super();
		
		// set the singleton instance of ClientManagerImpl class in the ClientManager so that
		// ClientManager.getInstance() also points to the singleton instance of ClientManagerImpl 
		setInstance(this);
	}
	
	/**
	* To make the singleton instance available to external classes
	*/
	public static ClientManagerImpl getInstance()
	{
		return singleton;
	}

	/**
	* Override this method so that it returns an instance of ClientManagedBean instead of ClientBean
	*/
	@Override
	public ClientBean createClientBean()
	{
		return new ClientManagedBean();
	}   
}
