




// ______________________________________________________
// Generated by sql2java - http://sql2java.sourceforge.net/
// jdbc driver used at code generation time: com.mysql.jdbc.Driver
//
// Author: Javed Kansi
// ______________________________________________________

package uk.co.planetbeyond.service.manager;

import uk.co.planetbeyond.service.generated.FactManager;
import uk.co.planetbeyond.service.generated.FactBean;
import uk.co.planetbeyond.service.managedbean.FactManagedBean;

/**
* If any change needs to be made to the FactManager, it MUST not be made directly
* Instead the FactManagerImpl class should be used to make the changes
*/
public class FactManagerImpl extends FactManager 
{
	/**
	* Singleton instance of this class
	*/
	private static FactManagerImpl singleton = new FactManagerImpl();
	
	/**
	* Make the constructor private to make the class singleton
	*/
	private FactManagerImpl()
	{
		super();
		
		// set the singleton instance of FactManagerImpl class in the FactManager so that
		// FactManager.getInstance() also points to the singleton instance of FactManagerImpl 
		setInstance(this);
	}
	
	/**
	* To make the singleton instance available to external classes
	*/
	public static FactManagerImpl getInstance()
	{
		return singleton;
	}

	/**
	* Override this method so that it returns an instance of FactManagedBean instead of FactBean
	*/
	@Override
	public FactBean createFactBean()
	{
		return new FactManagedBean();
	}   
}
