




// ______________________________________________________
// Generated by sql2java - http://sql2java.sourceforge.net/
// jdbc driver used at code generation time: com.mysql.jdbc.Driver
//
// Author: Javed Kansi
// ______________________________________________________

package uk.co.planetbeyond.service.manager;

import uk.co.planetbeyond.service.generated.LoyaltyStatsManager;
import uk.co.planetbeyond.service.generated.LoyaltyStatsBean;
import uk.co.planetbeyond.service.managedbean.LoyaltyStatsManagedBean;

/**
* If any change needs to be made to the LoyaltyStatsManager, it MUST not be made directly
* Instead the LoyaltyStatsManagerImpl class should be used to make the changes
*/
public class LoyaltyStatsManagerImpl extends LoyaltyStatsManager 
{
	/**
	* Singleton instance of this class
	*/
	private static LoyaltyStatsManagerImpl singleton = new LoyaltyStatsManagerImpl();
	
	/**
	* Make the constructor private to make the class singleton
	*/
	private LoyaltyStatsManagerImpl()
	{
		super();
		
		// set the singleton instance of LoyaltyStatsManagerImpl class in the LoyaltyStatsManager so that
		// LoyaltyStatsManager.getInstance() also points to the singleton instance of LoyaltyStatsManagerImpl 
		setInstance(this);
	}
	
	/**
	* To make the singleton instance available to external classes
	*/
	public static LoyaltyStatsManagerImpl getInstance()
	{
		return singleton;
	}

	/**
	* Override this method so that it returns an instance of LoyaltyStatsManagedBean instead of LoyaltyStatsBean
	*/
	@Override
	public LoyaltyStatsBean createLoyaltyStatsBean()
	{
		return new LoyaltyStatsManagedBean();
	}   
}
