




// ______________________________________________________
// Generated by sql2java - http://sql2java.sourceforge.net/
// jdbc driver used at code generation time: com.mysql.jdbc.Driver
//
// Author: Javed Kansi
// ______________________________________________________

package uk.co.planetbeyond.service.manager;

import uk.co.planetbeyond.service.generated.MessageAlertsManager;
import uk.co.planetbeyond.service.generated.MessageAlertsBean;
import uk.co.planetbeyond.service.managedbean.MessageAlertsManagedBean;

/**
* If any change needs to be made to the MessageAlertsManager, it MUST not be made directly
* Instead the MessageAlertsManagerImpl class should be used to make the changes
*/
public class MessageAlertsManagerImpl extends MessageAlertsManager 
{
	/**
	* Singleton instance of this class
	*/
	private static MessageAlertsManagerImpl singleton = new MessageAlertsManagerImpl();
	
	/**
	* Make the constructor private to make the class singleton
	*/
	private MessageAlertsManagerImpl()
	{
		super();
		
		// set the singleton instance of MessageAlertsManagerImpl class in the MessageAlertsManager so that
		// MessageAlertsManager.getInstance() also points to the singleton instance of MessageAlertsManagerImpl 
		setInstance(this);
	}
	
	/**
	* To make the singleton instance available to external classes
	*/
	public static MessageAlertsManagerImpl getInstance()
	{
		return singleton;
	}

	/**
	* Override this method so that it returns an instance of MessageAlertsManagedBean instead of MessageAlertsBean
	*/
	@Override
	public MessageAlertsBean createMessageAlertsBean()
	{
		return new MessageAlertsManagedBean();
	}   
}
