




// ______________________________________________________
// Generated by sql2java - http://sql2java.sourceforge.net/
// jdbc driver used at code generation time: com.mysql.jdbc.Driver
//
// Author: Javed Kansi
// ______________________________________________________

package uk.co.planetbeyond.service.manager;

import uk.co.planetbeyond.service.generated.OfferCategoryManager;
import uk.co.planetbeyond.service.generated.OfferCategoryBean;
import uk.co.planetbeyond.service.managedbean.OfferCategoryManagedBean;

/**
* If any change needs to be made to the OfferCategoryManager, it MUST not be made directly
* Instead the OfferCategoryManagerImpl class should be used to make the changes
*/
public class OfferCategoryManagerImpl extends OfferCategoryManager 
{
	/**
	* Singleton instance of this class
	*/
	private static OfferCategoryManagerImpl singleton = new OfferCategoryManagerImpl();
	
	/**
	* Make the constructor private to make the class singleton
	*/
	private OfferCategoryManagerImpl()
	{
		super();
		
		// set the singleton instance of OfferCategoryManagerImpl class in the OfferCategoryManager so that
		// OfferCategoryManager.getInstance() also points to the singleton instance of OfferCategoryManagerImpl 
		setInstance(this);
	}
	
	/**
	* To make the singleton instance available to external classes
	*/
	public static OfferCategoryManagerImpl getInstance()
	{
		return singleton;
	}

	/**
	* Override this method so that it returns an instance of OfferCategoryManagedBean instead of OfferCategoryBean
	*/
	@Override
	public OfferCategoryBean createOfferCategoryBean()
	{
		return new OfferCategoryManagedBean();
	}   
}
