




// ______________________________________________________
// Generated by sql2java - http://sql2java.sourceforge.net/
// jdbc driver used at code generation time: com.mysql.jdbc.Driver
//
// Author: Javed Kansi
// ______________________________________________________

package uk.co.planetbeyond.service.manager;

import uk.co.planetbeyond.service.generated.OfferOfTheDayManager;
import uk.co.planetbeyond.service.generated.OfferOfTheDayBean;
import uk.co.planetbeyond.service.managedbean.OfferOfTheDayManagedBean;

/**
* If any change needs to be made to the OfferOfTheDayManager, it MUST not be made directly
* Instead the OfferOfTheDayManagerImpl class should be used to make the changes
*/
public class OfferOfTheDayManagerImpl extends OfferOfTheDayManager 
{
	/**
	* Singleton instance of this class
	*/
	private static OfferOfTheDayManagerImpl singleton = new OfferOfTheDayManagerImpl();
	
	/**
	* Make the constructor private to make the class singleton
	*/
	private OfferOfTheDayManagerImpl()
	{
		super();
		
		// set the singleton instance of OfferOfTheDayManagerImpl class in the OfferOfTheDayManager so that
		// OfferOfTheDayManager.getInstance() also points to the singleton instance of OfferOfTheDayManagerImpl 
		setInstance(this);
	}
	
	/**
	* To make the singleton instance available to external classes
	*/
	public static OfferOfTheDayManagerImpl getInstance()
	{
		return singleton;
	}

	/**
	* Override this method so that it returns an instance of OfferOfTheDayManagedBean instead of OfferOfTheDayBean
	*/
	@Override
	public OfferOfTheDayBean createOfferOfTheDayBean()
	{
		return new OfferOfTheDayManagedBean();
	}   
}
