




// ______________________________________________________
// Generated by sql2java - http://sql2java.sourceforge.net/
// jdbc driver used at code generation time: com.mysql.jdbc.Driver
//
// Author: Javed Kansi
// ______________________________________________________

package uk.co.planetbeyond.service.manager;

import uk.co.planetbeyond.service.generated.OtpVerificationManager;
import uk.co.planetbeyond.service.generated.OtpVerificationBean;
import uk.co.planetbeyond.service.managedbean.OtpVerificationManagedBean;

/**
* If any change needs to be made to the OtpVerificationManager, it MUST not be made directly
* Instead the OtpVerificationManagerImpl class should be used to make the changes
*/
public class OtpVerificationManagerImpl extends OtpVerificationManager 
{
	/**
	* Singleton instance of this class
	*/
	private static OtpVerificationManagerImpl singleton = new OtpVerificationManagerImpl();
	
	/**
	* Make the constructor private to make the class singleton
	*/
	private OtpVerificationManagerImpl()
	{
		super();
		
		// set the singleton instance of OtpVerificationManagerImpl class in the OtpVerificationManager so that
		// OtpVerificationManager.getInstance() also points to the singleton instance of OtpVerificationManagerImpl 
		setInstance(this);
	}
	
	/**
	* To make the singleton instance available to external classes
	*/
	public static OtpVerificationManagerImpl getInstance()
	{
		return singleton;
	}

	/**
	* Override this method so that it returns an instance of OtpVerificationManagedBean instead of OtpVerificationBean
	*/
	@Override
	public OtpVerificationBean createOtpVerificationBean()
	{
		return new OtpVerificationManagedBean();
	}   
}
