




// ______________________________________________________
// Generated by sql2java - http://sql2java.sourceforge.net/
// jdbc driver used at code generation time: com.mysql.jdbc.Driver
//
// Author: Javed Kansi
// ______________________________________________________

package uk.co.planetbeyond.service.manager;

import uk.co.planetbeyond.service.generated.PromoManager;
import uk.co.planetbeyond.service.generated.PromoBean;
import uk.co.planetbeyond.service.managedbean.PromoManagedBean;

/**
* If any change needs to be made to the PromoManager, it MUST not be made directly
* Instead the PromoManagerImpl class should be used to make the changes
*/
public class PromoManagerImpl extends PromoManager 
{
	/**
	* Singleton instance of this class
	*/
	private static PromoManagerImpl singleton = new PromoManagerImpl();
	
	/**
	* Make the constructor private to make the class singleton
	*/
	private PromoManagerImpl()
	{
		super();
		
		// set the singleton instance of PromoManagerImpl class in the PromoManager so that
		// PromoManager.getInstance() also points to the singleton instance of PromoManagerImpl 
		setInstance(this);
	}
	
	/**
	* To make the singleton instance available to external classes
	*/
	public static PromoManagerImpl getInstance()
	{
		return singleton;
	}

	/**
	* Override this method so that it returns an instance of PromoManagedBean instead of PromoBean
	*/
	@Override
	public PromoBean createPromoBean()
	{
		return new PromoManagedBean();
	}   
}
