




// ______________________________________________________
// Generated by sql2java - http://sql2java.sourceforge.net/
// jdbc driver used at code generation time: com.mysql.jdbc.Driver
//
// Author: Javed Kansi
// ______________________________________________________

package uk.co.planetbeyond.service.manager;

import uk.co.planetbeyond.service.generated.SubscriberStatsManager;
import uk.co.planetbeyond.service.generated.SubscriberStatsBean;
import uk.co.planetbeyond.service.managedbean.SubscriberStatsManagedBean;

/**
* If any change needs to be made to the SubscriberStatsManager, it MUST not be made directly
* Instead the SubscriberStatsManagerImpl class should be used to make the changes
*/
public class SubscriberStatsManagerImpl extends SubscriberStatsManager 
{
	/**
	* Singleton instance of this class
	*/
	private static SubscriberStatsManagerImpl singleton = new SubscriberStatsManagerImpl();
	
	/**
	* Make the constructor private to make the class singleton
	*/
	private SubscriberStatsManagerImpl()
	{
		super();
		
		// set the singleton instance of SubscriberStatsManagerImpl class in the SubscriberStatsManager so that
		// SubscriberStatsManager.getInstance() also points to the singleton instance of SubscriberStatsManagerImpl 
		setInstance(this);
	}
	
	/**
	* To make the singleton instance available to external classes
	*/
	public static SubscriberStatsManagerImpl getInstance()
	{
		return singleton;
	}

	/**
	* Override this method so that it returns an instance of SubscriberStatsManagedBean instead of SubscriberStatsBean
	*/
	@Override
	public SubscriberStatsBean createSubscriberStatsBean()
	{
		return new SubscriberStatsManagedBean();
	}   
}
