




// ______________________________________________________
// Generated by sql2java - http://sql2java.sourceforge.net/
// jdbc driver used at code generation time: com.mysql.jdbc.Driver
//
// Author: Javed Kansi
// ______________________________________________________

package uk.co.planetbeyond.service.manager;

import uk.co.planetbeyond.service.generated.WebUserManager;
import uk.co.planetbeyond.service.generated.WebUserBean;
import uk.co.planetbeyond.service.managedbean.WebUserManagedBean;

/**
* If any change needs to be made to the WebUserManager, it MUST not be made directly
* Instead the WebUserManagerImpl class should be used to make the changes
*/
public class WebUserManagerImpl extends WebUserManager 
{
	/**
	* Singleton instance of this class
	*/
	private static WebUserManagerImpl singleton = new WebUserManagerImpl();
	
	/**
	* Make the constructor private to make the class singleton
	*/
	private WebUserManagerImpl()
	{
		super();
		
		// set the singleton instance of WebUserManagerImpl class in the WebUserManager so that
		// WebUserManager.getInstance() also points to the singleton instance of WebUserManagerImpl 
		setInstance(this);
	}
	
	/**
	* To make the singleton instance available to external classes
	*/
	public static WebUserManagerImpl getInstance()
	{
		return singleton;
	}

	/**
	* Override this method so that it returns an instance of WebUserManagedBean instead of WebUserBean
	*/
	@Override
	public WebUserBean createWebUserBean()
	{
		return new WebUserManagedBean();
	}   
}
